### ISSUE TITLE
Jupyter Server Roadmap

### ISSUE THREAD

**Issue by Zsailer** [jupyter/jupyter_server#127]
- [ ] Rename notebook_shim to **nbclassic**. 
        - [x] a notebook `ExtensionApp` (from jupyter_server).
        - [x] pulls Notebook JS and templates from `notebook`.
        - [ ] execute from command line with `jupyter nbclassic`
        - [ ] migrates configuration to `jupyter_server_config`.
    - [ ] Update Jupyter Server JEP to reflect new nbclassic.
    - [ ] Merge Kernel Providers
        - [ ] Move jupyter_kernel_mgmt, jupyter_protocol to Jupyter's Github org.
        - [ ] Documentation for Kernel Providers, jupyter_kernel_mgmt and jupyter_protocol.
        - [ ] Merge Kernel Providers into jupyter_server: jupyter/jupyter_server#112.
        - [ ] Help voila adjust to kernel_mgmt
            - @kevin-bates mentioned that he spoke with @SylvainCorlay about KP.
        - [ ] Release jupyter_server with Kernel Providers
        - [ ] Help`nb_conda_kernels` switch to Kernel Providers.
            - They currently have an old version of Kernel Provider.
            - nb_conda_kernels tries to import Kernel Providers. If found, uses the new kernel management framework. Otherwise, falls back to old way.
    - [ ] Transition JupyterLab to Jupyter Server, dropping notebook as a dependency.
        - Uses nbclassic to run notebook and lab side-by-side.
    - [ ] Notebook 7.x: transition jupyter/notebook to Jupyter Server
        - [ ] drop the old notebook server
        - [ ] NotebookApp becomes
        - [ ] shim the notebook server API to jupyter_server
        - [ ] raise DeprecationWarnings in shimmed APIs.
        - [ ] release notebook 7.x
    - [ ] Notebook 8.x: drop shims.

**Comment by Zsailer** [comment]
Just moved `Zsailer/notebook_shim` to `Zsailer/nbclassic`.

NBClassic is a thin package that provides the classic Jupyter Notebook frontend on top of Jupyter Server. You can install NBClassic side-by-side with `notebook`. NBClassic uses the Javascript and templates from notebook, but runs on the Jupyter Server's tornado server (not the notebook's native tornado server).

You can install nbclassic from PyPI today.
```
pip install jupyter_server nbclassic notebook
```
You can try the nbclassic frontend by running `jupyter server` or `jupyter nbclassic` and going to `localhost:<port>/tree?token=...`

**Comment by willingc** [comment]
@Zsailer I've gone ahead and pinned this issue for visibility. Thanks for putting it together!

**Comment by Zsailer** [comment]
Thanks, @willingc!

**Comment by echarles** [comment]
didn't know about the pinned feature, learning every day here... 

Good to have more visibility here but further actions could be needed in downstream projects that are using notebook or are/will be using server. This is especially true for the kernel_mgmt - nbclassic should have 0 impact I believe.

**Comment by echarles** [comment]
See https://github.com/jupyter/jupyter_server/issues/190
