### ISSUE TITLE
Sync Notebook and Jupyter Server.

### ISSUE THREAD

**Issue by Zsailer** [jupyter/jupyter_server#53]
Opening this issue to track the porting of relevant Notebook PRs to Jupyter Server. 

List to Port: 

- [x] jupyter/notebook#3664
- [x] jupyter/notebook#3759
- [x] jupyter/notebook#3778
- [x] jupyter/notebook#3789
- [x] jupyter/notebook#3799
- [x] jupyter/notebook#3806
- [x] jupyter/notebook#3809
- [x] jupyter/notebook#3829
- [x] jupyter/notebook#3879
- [x] jupyter/notebook#3883
- [x] jupyter/notebook#3886
- [x] jupyter/notebook#3907
- [x] jupyter/notebook#4034
- [x] jupyter/notebook#4036
- [x] jupyter/notebook#4063
- [x] jupyter/notebook#4099
- [x] jupyter/notebook#4103
- [x] jupyter/notebook#4112
- [x] jupyter/notebook#4139
- [x] jupyter/notebook#4161  (via #92)
- [x] jupyter/notebook#4210
- [x] jupyter/notebook#4219
- [x] jupyter/notebook#4235
- [x] jupyter/notebook#4260
- [x] jupyter/notebook#4284
- [x] jupyter/notebook#4328
- [x] jupyter/notebook#4355
- [x] jupyter/notebook#4376
- [x] jupyter/notebook#4392
- [x] jupyter/notebook#4412
- [x] jupyter/notebook#4426
- [x] jupyter/notebook#4431  (via #92)
- [x] jupyter/notebook#4449
- [x] jupyter/notebook#4453
- [x] jupyter/notebook#4468
- [x] jupyter/notebook#4519
- [x] jupyter/notebook#4528
- [x] jupyter/notebook#4531
- [x] jupyter/notebook#4576  (via #92)
- [x] jupyter/notebook#4618
- [x] jupyter/notebook#4672
- [x] jupyter/notebook#4674
- [x] jupyter/notebook#4701  (via #92)
- [x] jupyter/notebook#4724  (via #92)
- [x] jupyter/notebook#4725  (via #92)
- [x] jupyter/notebook#4756
- [x] jupyter/notebook#4777  (via #92)
- [x] jupyter/notebook#4891

My strategy is to just manually move PRs that affect files in the Server. Is that the best strategy here? @SylvainCorlay @blink1073

**Comment by blink1073** [comment]
As a last resort, sure. I'm wondering if Sylvain had some git-foo that he used last time. 😀

**Comment by Zsailer** [comment]
@SylvainCorlay, Sensei, teach us your git-foo ways! 😃

**Comment by kevin-bates** [comment]
Assuming this is the place to talk about NB PRs we want in server..

The Gateway related PRs are needed:  https://github.com/jupyter/notebook/pull/4161, https://github.com/jupyter/notebook/pull/4431 and the yet-to-be-merged https://github.com/jupyter/notebook/pull/4576.  These will enable the ability to manage kernels on computer cluster edge nodes, separated from the notebooks themselves.

I also believe jupyter server should introduce async kernel management, so (minor, but merged) PR https://github.com/jupyter/notebook/pull/4412 should probably be taken, but we should strongly consider the yet-to-be-merged PR https://github.com/jupyter/notebook/pull/4479 (which depends on jupyter client PR https://github.com/jupyter/jupyter_client/pull/428).  These last two enable the ability to change management class hierarchies from sync to async and I would propose we have the _default_ be async (the PR uses sync as the default since it was targeting Notebook).  Actually, this topic should probably become a separate issue.

If necessary, I'd be happy to help triage various notebook PRs for their applicability into server. 

Thanks.

**Comment by Zsailer** [comment]
Absolutely. I will definitely make sure to port these PRs over. I think the intention is to port anything that touches server-side code in the notebook. 

Before you spend too much time triaging notebook PRs, let's see if @SylvainCorlay has any tricks up his sleeve...

**Comment by lresende** [comment]
I believe @SylvainCorlay mentioned in the workshop that @Carreau has a tool that helps identifies all prs that touch a set of files or something like that which could help us identify the changes that need to be moved.

**Comment by SylvainCorlay** [comment]
I don't think that there is much magic we can do besides manually porting the PRs at this point.

**Comment by Zsailer** [comment]
Okay, I think it's time to start building a list of PRs to port. I'll edit the top post with a running checklist. If anyone wants to begin triaging PRs in notebook and listing them here, I'll update the checklist as we go.

**Comment by Zsailer** [comment]
Also, if anyone wants to port a PR, go ahead! 😄 I'll start working through this list, but any help is appreciated.

**Comment by Zsailer** [comment]
Also, here's a list of [notebook PRs](https://github.com/jupyter/notebook/pulls?utf8=%E2%9C%93&q=is%3Apr+merged%3A%3E2018-07-18+language%3Apython+) that were merged after @SylvainCorlay did the initial fork. Many of these PRs are frontend specific.

**Comment by Zsailer** [comment]
I've updated the top comment to include the full list of **merged** PRs in notebook that touch server_side code. Many of the changes are small. 

What's the best strategy to move forward?  

My plan was to
1. cherry-pick each of these changes in one major PR.
2. starting tracking notebook repo for server-side changes. 
3. manually port PRs to server as they land in notebook. 

Any better strategies?

**Comment by kevin-bates** [comment]
Thanks Zach.  I think steps 2 and 3 are fine.  Step 1 is probably the real question.  One massive PR seems like it could be a nightmare if issues arise.  I'm wondering if it would be better to chunk things up given they were independent changes previously.  Perhaps a "series" of 3 to 5 PRs?  Would that approach be helpful  for checkpointing progress?

I'm curious if you found changes that spanned into what would be the "nb classic" server extension?

Btw, the various Gateway PRs are addressed in #92.  I'll update the comment tomorrow - checking the applicable entries (with a reference to #92) if you're okay with that.

**Comment by Zsailer** [comment]
>  chunk things up given they were independent changes previously

I think you're right. Let's break it up. I'm planning to move through these pretty fast, so I'll open multiple batches of PRs.

I didn't track any PRs that were nbclassic specific. I'll probably rebase jupyter/notebook#4653, allowing us to start fresh on tracking PRs for nbclassic.

> Btw, the various Gateway PRs are addressed in #92. I'll update the comment tomorrow - checking the applicable entries (with a reference to #92) if you're okay with that.

Great! #92 is what inspired me to build the above checklist. I'd love to stay on top of notebook PRs moving forward. Thanks for doing this great work!

**Comment by kevin-bates** [comment]
@Zsailer - I've updated the comment to indicate those gateway-related PRs handled in #92.  There's also one gateway-related commit from #4449 that you'll find already done (be35a370c).

**Comment by Zsailer** [comment]
Question for the group—should we squash merge the ported PRs? Or should we retain the full commit history?

**Comment by lresende** [comment]
I personally really don't like the option to see the PR history in master, it makes it very messy, particularly as a lot of people add committs to a pr like 'fix typo' or 'another try'... Also, if someone is really interested in the pr lifecycle, comments, history, this is still available on the pr. 

Having said that, in this particular case, this is cherry-picking multiple commits, so I would just `rebase and merge` which would maintain the history.

**Comment by kevin-bates** [comment]
I agree.  I think moving forward, we should try to adopt a `squash and merge` approach for multi-commit PRs.  But, as Luciano says, since these are essentially multi-PR PRs, where each PR is  potentially multiple commits, I think it makes sense to not squash in this case.

**Comment by Zsailer** [comment]
Great, thanks everyone. Check out #96 for our plan to move forward.

**Comment by vidartf** [comment]
I'm mostly against squashing due to it making `git blame` (especially here in github) a lot harder to navigate. However, I'm for it under these circumstances:
- The individual commits change some code, then changes it back to the original value (reversion). In these cases squashes make for a cleaner history.
- The total line changes are small (implying that it doesn't conflate changes that are logically different).

**Comment by Zsailer** [comment]
🎉  🎉  I think we've successfully synced jupyter_server with the classic notebook server (huge thank you to @kevin-bates for reviewing these PRs)!  🎉  🎉 

I'll be tracking notebook to make sure we port PRs here as they land in notebook.

**Comment by kevin-bates** [comment]
Thanks for the great work Zach!  Time to rock this thing! 🚀
